### ISSUE TITLE
两张图看的好迷惑

### ISSUE THREAD

**Issue by codlin** [wmpf/wmpf_demo_external#1]
请教：
WMPF Service，WMPF Server，WMPF Client、WMPF Client “桌面 App”和小程序框架，请问它们的关系是什么？
WMPF（程序框架）由两部分组成：WMPF Server apk && WMPF Client apk
第二张图，小程序框架指的是server?

谢谢

**Comment by simonla** [comment]
首先回答下WMPF Server，这是笔误带来的不存在的概念，现在已经更新了文档

**Comment by simonla** [comment]
接下来回答一下WMPF Service、小程序框架、WMPF Client、 “桌面 App”的关系

先说下WMPF Server和小程序框架的关系。小程序框架本来是存在在微信中的，我们单独把它抽象了出来，放在了WMPF Server Apk里，这样这个Apk就可以运行小程序了，所以可以理解为WMPF Server包含了小程序框架，代表了运行小程序的能力

然后说下WMPF Client。我们知道Android有Launcher的概念，用来启动Android App。同样的，开发者可以开发自己的"桌面 app"来启动小程序，这个app被称作WMPF Client

**Comment by codlin** [comment]
多谢～
