### ISSUE TITLE
使用最新小程序框架体验demo输入appid无法启动体验版小程序

### ISSUE THREAD

**Issue by AlexYXB** [wmpf/wmpf_demo_external#10]
刚才下载了”输入小程序App ID和Ticket即可体验demo“版本的demo，安装后点击**登录**仍然提示”E/FastExperienceActivity: error: java.lang.IllegalStateException: it.invokeToken must not be null“

然后点击**启动体验版小程序（必须先登陆）**提示：”E/FastExperienceActivity: success: com.tencent.wmpf.proto.WMPFLaunchWxaAppResponse@e828d9f“

首先咨询该如何的处理，其次是否可以把错误信息报的更明确些？或者给一个错误信息参照表？

**Comment by simonla** [comment]
登陆需要先走硬件注册流程激活设备

如果只需要快速体验，可以按照readme描述的步骤，启动小程序试试
