### ISSUE TITLE
WMPF 开发中，激活设备一直报10014 signature err,但签名校验成功，什么原因？

### ISSUE THREAD

**Issue by calvinklein86** [wmpf/wmpf_demo_external#101]
切换到guide渠道的时候，执行demo的STEP1.1 ACTIVATE DEVICE报错：

error: TaskErrorException(taskError=TaskError{errType=1, errCode=10014, errMsg=signature err 0})

但实际上，我的签名校验显示成功的

[root@iZwz9dbqod4z54pyobhhuwZ test]# sudo bash ./test.sh verify_ecdsa_sign 1757 VB0119CA00472 pubkey_filepath sign_filepath
Signature Verified Successfully

这是怎么回事呢？具体步骤写在这里了
[https://developers.weixin.qq.com/community/develop/doc/000800347c84b04cce2bf096d51800](url)

**Comment by simonla** [comment]
已解决
