### ISSUE TITLE
wmpf arm install error

### ISSUE THREAD

**Issue by DongJigong** [wmpf/wmpf_demo_external#103]
![image](https://user-images.githubusercontent.com/8855265/98761801-2fcdea00-2411-11eb-98d4-c2d636205c07.png)
1.0.4

**Comment by DongJigong** [comment]
It works fine on real device. I think maybe my env has something different

**Comment by zhoujia456888** [comment]
尝试安装arm的版本，不安装arm64位版本。我刚刚也遇到这个问题了。安装arm64版本报错，arm版本安装成功。

**Comment by DongJigong** [comment]
> 尝试安装arm的版本，不安装arm64位版本。我刚刚也遇到这个问题了。安装arm64版本报错，arm版本安装成功。

Thanks for your reply!
