### ISSUE TITLE
请你们规范好WMPF的版本名称

### ISSUE THREAD

**Issue by zhoujia456888** [wmpf/wmpf_demo_external#104]
安装的wmpf-arm-production-release-v1.0.4-rc3-630.apk这个软件，实际版本名称是8.0.4.3。你们的版本名称这么随意的吗。
v1.0.4这个从何而来？我该如何判断版本去升级WMPF框架？
![image](https://user-images.githubusercontent.com/7905253/99021666-202edc80-259c-11eb-9042-f48a35280f66.png)

**Comment by zhoujia456888** [comment]
我现在只能先根据版本号630这个去判断是否需要升级。但是据我所知，你们Release v1.0.4-RC2和Release v1.0.4-RC1这两个版本，版本号都是600。这就让我点迷茫了。
![image](https://user-images.githubusercontent.com/7905253/99023739-2c1c9d80-25a0-11eb-95c7-7cc964ca1d3b.png)
![image](https://user-images.githubusercontent.com/7905253/99023720-23c46280-25a0-11eb-89bf-75c27f96c4ad.png)

**Comment by simonla** [comment]
这里会想下办法自动化，感谢～
