### ISSUE TITLE
设备管理的-机型审核一直没有人审核

### ISSUE THREAD

**Issue by songshuangfeng** [wmpf/wmpf_demo_external#105]
设备管理的-机型审核一直没有人审核，我看文档上写的是约1-3个工作日。目前都5个多工作日了还没有审核，请尽快处理一下。
帐号：songshuangfeng@vchangyi.com

**Comment by Hazy-Huang** [comment]
查了一下，这个账号下只申请了一个设备机型，在11月11日就已经通过了，可以麻烦贴一下截图吗？

**Comment by songshuangfeng** [comment]
> 查了一下，这个账号下只申请了一个设备机型，在11月11日就已经通过了，可以麻烦贴一下截图吗？
目前看到已审核了，谢谢
