### ISSUE TITLE
wmpf如何打通原生app的sdk能力呢？

### ISSUE THREAD

**Issue by jrz90000** [wmpf/wmpf_demo_external#12]
目前用的react-native开发的app，里面嵌入了如微信刷脸等sdk，可以用桥接的模式，支持这个服务。然而研究了一下wmpf，发现没有小程序和原生app通信的接口。
我们目前想的模式：
调用方法，wmpf->app->sdk->返回消息->app->wmpf。这种流程。

**Comment by simonla** [comment]
你的意思是，WMPF是否支持小程序的js代码直接调用到client端的代码？

**Comment by jrz90000** [comment]
对的。类似https://facebook.github.io/react-native/docs/native-modules-android 我的理解下来，我的传感器，业务相关sdk这样才能打通。

**Comment by simonla** [comment]
1.0.1已支持invokeChannel
https://github.com/wmpf/wmpf_demo_external/releases/tag/v1.0.1-RC1
