### ISSUE TITLE
运行体验版的第三方小程序报错误：tdi session already been destroyed!!

### ISSUE THREAD

**Issue by TaoHanny** [wmpf/wmpf_demo_external#15]
您好！我使用最新的wmpf运行体验版的第三方小程序，报如下错误：
`02-10 17:16:26.774 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:16:51.595 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:17:05.494 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:17:43.603 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:18:16.450 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:18:29.865 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:19:37.346 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:20:01.495 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:20:27.546 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!
02-10 17:21:03.320 E/IlinkServiceTdiImpl( 5170): tdi session already been destroyed!!`
我的Android环境应该没有问题，已经成功的跑通了自己的微信小程序，所以这个错误是什么意思？

**Comment by TaoHanny** [comment]
再补充一下现象：我运行体验版小程序，Android手机上可以正常运行，一旦到我们自己的硬件平台就发发生小程序运行1秒左右就闪退的现象。
`02-11 10:28:05.933 I/MagicBrush( 3238): [MessageQueue] loop, processing...
02-11 10:28:05.940 W/System.err( 3238): java.lang.UnsupportedOperationException: class org.xwalk.core.internal.XWalkViewBridge.setExtendTextAreaClientSuper
02-11 10:28:05.941 W/System.err( 3238): 	at org.xwalk.core.ReflectMethod.invoke(SourceFile:57)
02-11 10:28:05.941 W/System.err( 3238): 	at org.xwalk.core.XWalkView.setExtendTextAreaClient(SourceFile:1397)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.page.bj.<init>(XWebViewImpl.java:2073)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.l.g.b.b(MPPageViewRendererStandaloneXWebImpl.java:38)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.page.at.c(MPPageViewRenderer.java:10236)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.page.a.a(AbstractMPPageViewRenderer.java:313)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.page.t.c(AppBrandPageView.java:26430)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.jsapi.d.L(AppBrandComponentImpl.java:124)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.page.t.s(AppBrandPageView.java:210)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.wmpf.g.f$3$2$1.run(WMPFBaseRuntime.java:237)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.d.a(AppBrandRuntime.java:1272)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.wmpf.g.f$3$2.run(WMPFBaseRuntime.java:2259)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.wmpf.g.f$3$3.a(WMPFBaseRuntime.java:249)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.l.a.d.a(XWebPreloader.java:64)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.wmpf.g.f$3.a(WMPFBaseRuntime.java:246)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.d$12.run(AppBrandRuntime.java:1342)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.sdk.h.b.a(Profile.kt:25)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.d.z(AppBrandRuntime.java:237)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.mm.plugin.appbrand.e.a(AppBrandRuntimeContainer.java:199)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:20)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.sdk.f.a$1.run(AppBrandRuntimeContainerLU.java:51)
02-11 10:28:05.941 W/System.err( 3238): 	at android.app.Activity.runOnUiThread(Activity.java:5502)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:35)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.e.a.a(AppBrandRuntimeContainerStandaloneImpl.java:5028)
02-11 10:28:05.941 W/System.err( 3238): 	at com.tencent.luggage.e.a$1.run(AppBrandRuntimeContainerStandaloneImpl.java:81)
02-11 10:28:05.941 W/System.err( 3238): 	at android.os.Handler.handleCallback(Handler.java:739)
02-11 10:28:05.941 W/System.err( 3238): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-11 10:28:05.941 W/System.err( 3238): 	at android.os.Looper.loop(Looper.java:135)
02-11 10:28:05.941 W/System.err( 3238): 	at android.app.ActivityThread.main(ActivityThread.java:5280)
02-11 10:28:05.941 W/System.err( 3238): 	at java.lang.reflect.Method.invoke(Native Method)
02-11 10:28:05.941 W/System.err( 3238): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-11 10:28:05.941 W/System.err( 3238): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
02-11 10:28:05.941 W/System.err( 3238): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)`

这是我找到报错信息

**Comment by simonla** [comment]
> 再补充一下现象：我运行体验版小程序，Android手机上可以正常运行，一旦到我们自己的硬件平台就发发生小程序运行1秒左右就闪退的现象。
> `02-11 10:28:05.933 I/MagicBrush( 3238): [MessageQueue] loop, processing... 02-11 10:28:05.940 W/System.err( 3238): java.lang.UnsupportedOperationException: class org.xwalk.core.internal.XWalkViewBridge.setExtendTextAreaClientSuper 02-11 10:28:05.941 W/System.err( 3238): at org.xwalk.core.ReflectMethod.invoke(SourceFile:57) 02-11 10:28:05.941 W/System.err( 3238): at org.xwalk.core.XWalkView.setExtendTextAreaClient(SourceFile:1397) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.page.bj.<init>(XWebViewImpl.java:2073) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.l.g.b.b(MPPageViewRendererStandaloneXWebImpl.java:38) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.page.at.c(MPPageViewRenderer.java:10236) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.page.a.a(AbstractMPPageViewRenderer.java:313) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.page.t.c(AppBrandPageView.java:26430) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.jsapi.d.L(AppBrandComponentImpl.java:124) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.page.t.s(AppBrandPageView.java:210) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.wmpf.g.f$3$2$1.run(WMPFBaseRuntime.java:237) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.d.a(AppBrandRuntime.java:1272) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.wmpf.g.f$3$2.run(WMPFBaseRuntime.java:2259) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.wmpf.g.f$3$3.a(WMPFBaseRuntime.java:249) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.l.a.d.a(XWebPreloader.java:64) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.wmpf.g.f$3.a(WMPFBaseRuntime.java:246) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.d$12.run(AppBrandRuntime.java:1342) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.sdk.h.b.a(Profile.kt:25) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.d.z(AppBrandRuntime.java:237) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.mm.plugin.appbrand.e.a(AppBrandRuntimeContainer.java:199) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:20) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.sdk.f.a$1.run(AppBrandRuntimeContainerLU.java:51) 02-11 10:28:05.941 W/System.err( 3238): at android.app.Activity.runOnUiThread(Activity.java:5502) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.sdk.f.a.a(AppBrandRuntimeContainerLU.java:35) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.e.a.a(AppBrandRuntimeContainerStandaloneImpl.java:5028) 02-11 10:28:05.941 W/System.err( 3238): at com.tencent.luggage.e.a$1.run(AppBrandRuntimeContainerStandaloneImpl.java:81) 02-11 10:28:05.941 W/System.err( 3238): at android.os.Handler.handleCallback(Handler.java:739) 02-11 10:28:05.941 W/System.err( 3238): at android.os.Handler.dispatchMessage(Handler.java:95) 02-11 10:28:05.941 W/System.err( 3238): at android.os.Looper.loop(Looper.java:135) 02-11 10:28:05.941 W/System.err( 3238): at android.app.ActivityThread.main(ActivityThread.java:5280) 02-11 10:28:05.941 W/System.err( 3238): at java.lang.reflect.Method.invoke(Native Method) 02-11 10:28:05.941 W/System.err( 3238): at java.lang.reflect.Method.invoke(Method.java:372) 02-11 10:28:05.941 W/System.err( 3238): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 02-11 10:28:05.941 W/System.err( 3238): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)`
> 
> 这是我找到报错信息

麻烦贴下`/sdcard/wmpf/xlog/crash`这个目录下的文件呢

**Comment by TaoHanny** [comment]
不好意思，由于我昨天着急汇报测试结果，所以已将com.tencent.wmpf下的缓存给清理了。现在在`/sdcard/wmpf/xlog/`下没有发现crash文件，同时我清理缓存后没有再触发这个BUG。针对我昨天提交的问题，我需要做两个需要更正的地方：

- 这个bug并不分平台，我在Android手机和公司硬件平台都触发了这个问题，解决办法都是清理缓存；

- 这个BUG并不区分是第三方小程序或自家小程序都是能触发这个问题。

针对你要的crash下的文件，等我下次触发我会及时贴上来，谢谢！

**Comment by lvandroid** [comment]
我也遇到相同的bug，下载编译好的那个快速体验的demo可以启动已经发布的apk，自己编译这个项目后启动小程序会闪退，也没有crash这个文件夹

**Comment by simonla** [comment]
1.0.1已fix
https://github.com/wmpf/wmpf_demo_external/releases/tag/v1.0.1-RC1
