### ISSUE TITLE
WMPF Client Demo -->>快速体验体验小程序，启动小程序失败

### ISSUE THREAD

**Issue by charjack** [wmpf/wmpf_demo_external#19]
运行demo工程，按照操作文档填写了appid以及ticket。调用Api.activateDevice返回激活成功（success 激活: com.tencent.wmpf.proto.WMPFActivateDeviceResponse@2d0723f errormsg= ret=0），然后运行Api.launchWxaApp，返回结果却是“response.baseResponse.errMsg = no activate response.baseResponse.ret=10006”。请问下这是什么原因？

**Comment by simonla** [comment]
提供下appId吧，谢谢

**Comment by charjack** [comment]
你好，相关参数如下（附件有相关截图）：wx94ef6bb77b573d05b2fcefb0c24eaa9a243528b0d91ee039wxd073f16e97f77d046339189558如图所示，已经提示success，但是实际没有调来小程序。--------------------------------


----- 原始邮件 -----
发件人：simonla <notifications@github.com>
收件人：wmpf/wmpf_demo_external <wmpf_demo_external@noreply.github.com>
抄送人：charjack <charjack@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[wmpf/wmpf_demo_external]_WMPF_Client_Demo_-->>快速体验体验小程序，启动小程序失败_(#19)
日期：2020年02月17日 15点34分

提供下appId吧，谢谢

**Comment by charjack** [comment]
请问下，“no activate  10006”是说设备没有激活吗？还是有其它问题会导致出现这个问题？

**Comment by Hazy-Huang** [comment]
旧WMPF存在问题，现最新版本WMPF已修复，麻烦更新一下新WMPF是否存在
