### ISSUE TITLE
上传接口使用微信服务号AppID，调用上传接口提示「api功能未授权」

### ISSUE THREAD

**Issue by mengdream** [wmpf/wmpf_demo_external#23]
设备已经审核通过，在上传接口中，使用了已经通过微信认证的服务号的AppID
![image](https://user-images.githubusercontent.com/3888694/74716123-ea590380-5268-11ea-9a7b-2b4588be5eeb.png)

使用上传接口`https://api.weixin.qq.com/wxa/business/runtime/adddevice?access_token=YOUR_ACCESS_TOKEN`， 进行硬件注册，提示
![image](https://user-images.githubusercontent.com/3888694/74716314-3d32bb00-5269-11ea-945f-06db763be319.png)

查看微信公众号平台后台接口权限，已经获得「设备功能接口」的权限
![image](https://user-images.githubusercontent.com/3888694/74716388-66534b80-5269-11ea-9b6d-013a6d6e167a.png)

我上述的操作中，哪一步是有问题的？

**Comment by mengdream** [comment]
刚刚使用开放平台下面的安卓应用的AppID可以上传了
![image](https://user-images.githubusercontent.com/3888694/74717541-8b48be00-526b-11ea-96cf-a2fd58739d80.png)


使用上传接口也进行了设备注册也成功了，但是在查询设备状态，提示「查询参数有误」
![image](https://user-images.githubusercontent.com/3888694/74717673-c0eda700-526b-11ea-9e83-8f841e08b05a.png)


那么怎么获得已经注册设备的`KeyVersion`
![image](https://user-images.githubusercontent.com/3888694/74717785-f5616300-526b-11ea-8256-69a2c007868e.png)

**Comment by simonla** [comment]
> 使用上传接口也进行了设备注册也成功了，但是在查询设备状态，提示「查询参数有误」


看起来是deviceID不对，有通过[后台接口](https://developers.weixin.qq.com/doc/oplatform/Miniprogram_Frame/deviceId.html)上传deviceID吗

**Comment by steven1984** [comment]
我也是遇到了同样的问题：在“申请后台接口”->上传接口功能中，使用https://api.weixin.qq.com/wxa/business/runtime/adddevice?access_token=YOUR_ACCESS_TOKEN， 进行硬件注册时：
1）第一种情况：使用已经通过微信认证的服务号的AppID（企业），使用我通过https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
获取access_token，但此时报40164错误：[调用接口的IP地址不在白名单中，请在接口IP白名单中进行设置]，按照说明应是在公众号平台添加白名单，但在_基本设置_里面没有此功能选项；
2）第二种情况：使用个人订阅号的APPID(个人)，情况一的IP白名单可以在公众号平台基本设置中添加，但报48001:api unauthorized hint。我想这跟公众号未认证有关；
3）第三种情况：使用小程序APP的APPID，可以使用adddevice接口上传成功（response返回OK），但“查询设备状态”中，报同样的“查询参数有误”。

我就有疑问：在硬件注册注册的环节，APPID是使用公众号或移动应用还是小程序的APPID？（虽然文档描述是公众号的APPID，但一直未成功。需要具备什么样的条件才能成功上传设备ID？）

**Comment by steven1984** [comment]
刚刚查阅了资料：第一种情况，我启用appsecret并设置白名单就可以获取access_token.
但不管第一种情况还是第二种情况，最终都是报48001:api unauthorized hint

**Comment by mengdream** [comment]
> > 使用上传接口也进行了设备注册也成功了，但是在查询设备状态，提示「查询参数有误」
> 
> 看起来是deviceID不对，有通过[后台接口](https://developers.weixin.qq.com/doc/oplatform/Miniprogram_Frame/deviceId.html)上传deviceID吗

有通过后台上传接口上传device_id，接口返回成功，errorcode为0

**Comment by simonla** [comment]
这里的appid不是公众号的，也不是小程序的，而是在公众平台申请的移动应用的appid

**Comment by steven1984** [comment]
> 这里的appid不是公众号的，也不是小程序的，而是在公众平台申请的移动应用的appid

我已经修改为移动应用的APPID，上传adddevice接口反馈OK。与mengdream一样的问题：
通过微信终端平台查询，提示查询参数错误;

若此时，调用IPCInvokerTask_ActivateDevice出错，进入onBridgeNotFound回调函数（相关参数检查正确无误）。
结合两者来看，应是后台未正确录入上传的设备或是相关设备绑定/权限有问题导致。
请调查一下 @simonla hostappid=wxa739dc51ee8bb312, deviceid=5ENDU19B08017968

**Comment by mengdream** [comment]
> 这里的appid不是公众号的，也不是小程序的，而是在公众平台申请的移动应用的appid

应该是这么理解的，前台的提示界面给了误导（提示的是找公众号的APPID）。

现在的问题是，查询设备状态还是提示错误，也不是提示找不到该硬件，而是提示「查询参数有误」。
