### ISSUE TITLE
小程序管理页面只有新增，无法删除

### ISSUE THREAD

**Issue by steven1984** [wmpf/wmpf_demo_external#24]
小程序管理页面只有管理按钮，无法删除，但wiki指导里面是有“删除”功能，这是怎么回事？
【我的】
![微信图片_20200218204037](https://user-images.githubusercontent.com/1251461/74737346-a3323900-528f-11ea-853e-abd53bcc0571.png)
【指导文档的】
![image](https://user-images.githubusercontent.com/1251461/74737575-1176fb80-5290-11ea-91f2-0060abe0b05d.png)

**Comment by simonla** [comment]
功能调整，我同步下文档的图片，感谢反馈☕️

**Comment by steven1984** [comment]
那功能调整后，可以进行小程序的绑定删除（即解绑定）吗？
