### ISSUE TITLE
激活设备失败，WMPFActivateDeviceResponse.errMsg= activate device fail: obtain token fail by ilink

### ISSUE THREAD

**Issue by steven1984** [wmpf/wmpf_demo_external#25]
执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。

这是什么错误？

**Comment by TaoHanny** [comment]
> 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> 
> 这是什么错误？

您好！我之前其实也一直在关注您在Issues中提交的另一个问题，其中您有提到`查询设备状态，提示「查询参数有误」`,这个问题你是已经解决了吗？因为我看到您的后续回复已经被删除了。

**Comment by steven1984** [comment]
> > 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> > 这是什么错误？
> 
> 您好！我之前其实也一直在关注您在Issues中提交的另一个问题，其中您有提到`查询设备状态，提示「查询参数有误」`,这个问题你是已经解决了吗？因为我看到您的后续回复已经被删除了。

是的。我是因为问题的回复有些问题，故而删掉了。 删掉的原因：onBridgeNotFound这个返回，通过深入研究，是由于WMPF Service未启动造成的。
提示「查询参数有误」，这个问题仍然存在，未解决。一直在跟踪微信管理人员的回复。

**Comment by simonla** [comment]
> 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> 
> 这是什么错误？

麻烦把手机/sdcard/wmpf/xlog下的log文件发到我的邮箱，我帮你看一下，邮箱是complexzeng@tencent.com

**Comment by steven1984** [comment]
> > 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> > 这是什么错误？
> 
> 麻烦把手机/sdcard/wmpf/xlog下的log文件发到我的邮箱，我帮你看一下，邮箱是[complexzeng@tencent.com](mailto:complexzeng@tencent.com)

问题日志和相关参数信息，已发至你的邮箱。请及时查阅和协助分析问题。谢谢

**Comment by TaoHanny** [comment]
请问调用activateDevice这个Task,返回
`/DocumentActivity: success: -1 activate device fail: obtain token fail by ilink `  
这个错误我也遇到了，返回这个的原因是什么？

**Comment by TaoHanny** [comment]
> > > 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> > > 这是什么错误？
> > 
> > 
> > 麻烦把手机/sdcard/wmpf/xlog下的log文件发到我的邮箱，我帮你看一下，邮箱是[complexzeng@tencent.com](mailto:complexzeng@tencent.com)
> 
> 问题日志和相关参数信息，已发至你的邮箱。请及时查阅和协助分析问题。谢谢

您好！这个问题您解决了吗？我也遇到相同的问题。在激活设备时，出现此错误‘activate device fail: obtain token fail by ilink’。

**Comment by simonla** [comment]
> > > > 执行激活设备task：val result = WMPFIPCInvoker.invokeAsync<IPCInvokerTask_ActivateDevice, WMPFActivateDeviceRequest, WMPFActivateDeviceResponse>，在response中反馈errMsg=activate device fail: obtain token fail by ilink。
> > > > 这是什么错误？
> > > 
> > > 
> > > 麻烦把手机/sdcard/wmpf/xlog下的log文件发到我的邮箱，我帮你看一下，邮箱是[complexzeng@tencent.com](mailto:complexzeng@tencent.com)
> > 
> > 
> > 问题日志和相关参数信息，已发至你的邮箱。请及时查阅和协助分析问题。谢谢
> 
> 您好！这个问题您解决了吗？我也遇到相同的问题。在激活设备时，出现此错误‘activate device fail: obtain token fail by ilink’。

检查注册流程，确保DeviceInfo、HOST_APPID、HOST_APPSECRET正确，特别注意DeviceInfo.signature中是不能有换行符的

**Comment by steven1984** [comment]
已经解决了，正如上面simonla所述：首先，你得保证你的hostAppID及secret正确，且addDevice上传设备Ok。 然后确认你的device signature是否正确，并且**signature不能含有\n符，我这就是这一步有问题的**。
可以参考如下截图
![20200226211421](https://user-images.githubusercontent.com/1251461/75348388-b079a400-58dd-11ea-9064-7285ce38845c.jpg)

**Comment by TaoHanny** [comment]
> 已经解决了，正如上面simonla所述：首先，你得保证你的hostAppID及secret正确，且addDevice上传设备Ok。 然后确认你的device signature是否正确，并且**signature不能含有\n符，我这就是这一步有问题的**。
> 可以参考如下截图
> ![20200226211421](https://user-images.githubusercontent.com/1251461/75348388-b079a400-58dd-11ea-9064-7285ce38845c.jpg)

您好！ 我检查了hostAPPID和Secret，我可以确保是正确的，因为我拿这两个参数在微信终端平台->绑定小程序界面输入这两个参数是绑定成功了的。deviceID和signture都进行了`sudo bash mmiot_ecdsa_sign.sh  verify_ecdsa_sign `验证是成功的，您这里强调**signature不能含有\n符**，那是不是意味着在微信终端平台->设备管理中输入公钥时，也不能有换行，我的公钥是有换行的，如下图  
![image](https://user-images.githubusercontent.com/30739724/75406400-56afc300-594b-11ea-8944-8b67d4ac7c76.png)
 所以，想请教一下您这边在微信终端平台输入公钥时，是把换行给去掉的吗？
