### ISSUE TITLE
Android 10手机上启动小程序后，显示空白页

### ISSUE THREAD

**Issue by steven1984** [wmpf/wmpf_demo_external#32]
Android 10手机(华为荣耀)上启动小程序后，显示空白页，如下图示。（尝试了不同的2个小程序，现象一样）
相比较Android9版本（原生android）没有此问题，可以正常渲染。
![20200226153408](https://user-images.githubusercontent.com/1251461/75322516-de46f480-58ad-11ea-8561-97734ca70425.jpg)

**Comment by TaoHanny** [comment]
https://github.com/wmpf/wmpf_demo_external/issues/25#issuecomment-589937689

您好！您之前提交的关于激活设备出现`activate device fail: obtain token fail by ilink`的问题，我目前也遇到了，但由于这个问题已经closed,同时官方没有在下面说明产生的原因，所以想请教您是如何解决这个问题以及是什么导致的。同时也很抱歉在您此Issues下回复不相干的内容，祝您生活愉快！

**Comment by simonla** [comment]
这个小程序进首页使用调用wx.authorize获取到用户信息后再进行内容的展示。 WMPF环境，没有登录的话wx.authorize会返回error， 所以白屏

这是开发者逻辑决定的

要避免这个问题，要么登录，要么调用WMPFAuthorizeNoLogin
