### ISSUE TITLE
QQ音乐小程序在WMPF框架中运行，歌曲播放功能失败

### ISSUE THREAD

**Issue by steven1984** [wmpf/wmpf_demo_external#33]
在正确绑定和启动QQ音乐小程序之后， QQ音乐小程序启动页正常，获取歌曲等等正常，但在歌曲播放时失败了，如下图示。
我比较过，在微信客户端中运行QQ音乐播放功能正常（网络环境一样）。

![20200226160317](https://user-images.githubusercontent.com/1251461/75324289-91651d00-58b1-11ea-9746-b6cf29b8f119.jpg)

**Comment by steven1984** [comment]
请WMPF框架团队的工程师排查一下， 我有一个推测的方向，因为看不到WMPF Service apk内部代码，仅仅是根据经验推测，仅供参考：
由于Android版本目前有https安全访问的要求，https://developer.android.google.cn/training/articles/security-config.html，
QQ小程序在获取音乐列表及详情这些地方，使用的是https，但在获取音乐文件音频流，使用却是http，同时WMPF service中未配置network_security_config.xml 及cleartextTrafficPermitted=true.
进而造成了访问不到音频数据。

**Comment by simonla** [comment]
排查后发现是qq音乐的decoder缺失，后面修复下
