### ISSUE TITLE
Dome中接口调用传值错误

### ISSUE THREAD

**Issue by zhoujia456888** [wmpf/wmpf_demo_external#34]
在FastExperienceActivity中的78行，getTestDeviceInfo传的是（appId, ticket, DeviceInfo.APP_ID）,实际上getTestDeviceInfo应该传（ticket: String,wxaAppId: String,hostAppId: String）
![QQ截图20200227113919](https://user-images.githubusercontent.com/7905253/75410275-5537c800-5956-11ea-9ec7-c7633bf295ed.png)
![QQ截图20200227114023](https://user-images.githubusercontent.com/7905253/75410277-579a2200-5956-11ea-8ae2-7d715c3370c0.png)
而且我有疑问getTestDeviceInfo中的wxaAppId和hostAppId有什么区别吗？

**Comment by TaoHanny** [comment]
> 在FastExperienceActivity中的78行，getTestDeviceInfo传的是（appId, ticket, DeviceInfo.APP_ID）,实际上getTestDeviceInfo应该传（ticket: String,wxaAppId: String,hostAppId: String）
> ![QQ截图20200227113919](https://user-images.githubusercontent.com/7905253/75410275-5537c800-5956-11ea-9ec7-c7633bf295ed.png)
> ![QQ截图20200227114023](https://user-images.githubusercontent.com/7905253/75410277-579a2200-5956-11ea-8ae2-7d715c3370c0.png)
> 而且我有疑问getTestDeviceInfo中的wxaAppId和hostAppId有什么区别吗？

（非官方）wxaAppId是小程序的APPID，hostAppId是在微信开放平台创建的移动应用AppId

**Comment by simonla** [comment]
closed by #35

**Comment by simonla** [comment]
wxaAppId是小程序appId，hostAppId是在公众平台注册的移动应用的appId
