### ISSUE TITLE
我按首页的gif输入，点击启动小程序后，小程序并没有启动 

### ISSUE THREAD

**Issue by aofong19871029** [wmpf/wmpf_demo_external#4]
我按首页的gif输入，点击启动小程序后，小程序并没有启动
输入我自己的小程序appid也没有启动

**Comment by aofong19871029** [comment]
设备激活需由厂商提供productId/keyVersion/deviceId/signature，目前DebugAssist只接受从以下文件路径读取:"/sdcard/wmpf_device_activate_params.json"，其中json格式如下:
{
    "productId": productId,
    "keyVersion": keyVersion,
    "deviceId": deviceId,
    "signature": signature
}

必须有这个文件才能调试demo吗?

**Comment by aofong19871029** [comment]
点击登录没什么响应

**Comment by simonla** [comment]
跑通硬件注册流程后，修改[Constants](https://github.com/wmpf/wmpf_demo_external/blob/master/wmpf-demo/app/src/main/java/com/tencent/luggage/demo/wxapi/Constants.kt)，即可使用demo运行小程序

**Comment by aofong19871029** [comment]
@simonla 跑通硬件注册流程
是要完成下面的步骤吗?

只有通过平台鉴权的设备才可运行WMPF。

① 添加设备- 请在“首页-设备管理”中，添加希望上线小程序框架的设备类型。

② 添加机型- 添加具体机型，“接入业务模块”项勾选“微信小程序框架”。

③ 注册接口- 完成设备及机型添加后，需要在“首页-上传接口”中，配置公众号AppID，注册后台接口并上传设备ID，查看如何注册deviceId接口。

第五步：开发实现 通过本文档以下的开发指引部分，实现LauncherAPP调用WMPF的能力。

第六步：绑定小程序 完成开发后，需在“微信小程序框架-小程序管理”页面输入移动应用AppID（即LauncherAPP的AppID），绑定该硬件设备要运行的小程序。查看如何绑定小程序。

**Comment by aofong19871029** [comment]
@simonla 注册硬件还要填什么出货量， 跑个demo 的步骤感觉很复杂啊， 你们能多点图文吗.

**Comment by jaylinhong** [comment]
审批要多久呢？电视端的有没有什么限制呢

**Comment by simonla** [comment]
> @simonla 跑通硬件注册流程
> 是要完成下面的步骤吗?
> 
> 只有通过平台鉴权的设备才可运行WMPF。
> 
> ① 添加设备- 请在“首页-设备管理”中，添加希望上线小程序框架的设备类型。
> 
> ② 添加机型- 添加具体机型，“接入业务模块”项勾选“微信小程序框架”。
> 
> ③ 注册接口- 完成设备及机型添加后，需要在“首页-上传接口”中，配置公众号AppID，注册后台接口并上传设备ID，查看如何注册deviceId接口。
> 
> 第五步：开发实现 通过本文档以下的开发指引部分，实现LauncherAPP调用WMPF的能力。
> 
> 第六步：绑定小程序 完成开发后，需在“微信小程序框架-小程序管理”页面输入移动应用AppID（即LauncherAPP的AppID），绑定该硬件设备要运行的小程序。查看如何绑定小程序。

是的，需要完成这些步骤

这里确实太繁琐了，预计本周会给出一个简化的新方案，新方案只需要在wecooper注册后即可跑通demo

**Comment by 1368025478** [comment]
繁琐什么的都还好。。。最主要都是我去微信终端合作平台 申请接入设备，已经等了6天多了 审核还是没有下来。我怀疑根本就没有审核团队在工作。。哪里不行至少拒绝一下

**Comment by simonla** [comment]
> > @simonla 跑通硬件注册流程
> > 是要完成下面的步骤吗?
> > 只有通过平台鉴权的设备才可运行WMPF。
> > ① 添加设备- 请在“首页-设备管理”中，添加希望上线小程序框架的设备类型。
> > ② 添加机型- 添加具体机型，“接入业务模块”项勾选“微信小程序框架”。
> > ③ 注册接口- 完成设备及机型添加后，需要在“首页-上传接口”中，配置公众号AppID，注册后台接口并上传设备ID，查看如何注册deviceId接口。
> > 第五步：开发实现 通过本文档以下的开发指引部分，实现LauncherAPP调用WMPF的能力。
> > 第六步：绑定小程序 完成开发后，需在“微信小程序框架-小程序管理”页面输入移动应用AppID（即LauncherAPP的AppID），绑定该硬件设备要运行的小程序。查看如何绑定小程序。
> 
> 是的，需要完成这些步骤
> 
> 这里确实太繁琐了，预计本周会给出一个简化的新方案，新方案只需要在wecooper注册后即可跑通demo

抱歉这里delay了，请再等待一下，再次抱歉

**Comment by HendySo** [comment]
简化版的已经可以成功运行了。在wecooper平台的快速体验下面下载最新的demo，启动里面的GetDeviceInfoActivity用生成的ticket可以拿到可以运行的设备信息，填入Constants即可成功拉起小程序了

**Comment by HendySo** [comment]
> 简化版的已经可以成功运行了。在wecooper平台的快速体验下面下载最新的demo，启动里面的GetDeviceInfoActivity用生成的ticket可以拿到可以运行的设备信息，填入Constants即可成功拉起小程序了

不知为何，最新的代码中Constants无法自动获取到体验用的device信息

**Comment by simonla** [comment]
> > 简化版的已经可以成功运行了。在wecooper平台的快速体验下面下载最新的demo，启动里面的GetDeviceInfoActivity用生成的ticket可以拿到可以运行的设备信息，填入Constants即可成功拉起小程序了
> 
> 不知为何，最新的代码中Constants无法自动获取到体验用的device信息

用最新的代码再试试

**Comment by rptang** [comment]
按照快速体验的步骤执行后，在FastExperienceActivity界面中，日志打印到--------启动小程序--------，无法拉起小程序

**Comment by simonla** [comment]
> 按照快速体验的步骤执行后，在FastExperienceActivity界面中，日志打印到--------启动小程序--------，无法拉起小程序

设备激活的log是否有异常？启动的小程序和ticket绑定的小程序是否是相同的？

**Comment by rptang** [comment]
log无异常，流程细节点都有仔细比对过，用的是小米Note3手机测试，如方便，还请指导下，比较着急调研，联系邮箱rptangCN@icloud.com

**Comment by zengwendi** [comment]
最新代码请问流程是GetDeviceInfoActivity用生成的ticket可以拿到可以运行的设备信息，填入DeviceInfo然后再用FastExperienceActivity 去填入启动小程序的Appid和wecooper获取的ticket吗

**Comment by simonla** [comment]
> 最新代码请问流程是GetDeviceInfoActivity用生成的ticket可以拿到可以运行的设备信息，填入DeviceInfo然后再用FastExperienceActivity 去填入启动小程序的Appid和wecooper获取的ticket吗

该流程免去了硬件注册的流程，但仅限与「体验」与「开发」之用，获取到的设备信息也可以填入DeviceInfo，用来开发，但是失效后需要重新填写一次

正式的流程仍然需要注册硬件，然后将固化下来的设备信息填入DeviceInfo

**Comment by zengwendi** [comment]
打开小程序登陆必须通过扫描登录吗？上送appid和这个用户在这个小程序的openid，能否进行登录

**Comment by zengwendi** [comment]
打开小程序获取用户信息必须先扫码登录吗？上送appid和这个用户在这个小程序的openid，能否进行登录

**Comment by simonla** [comment]
> 打开小程序获取用户信息必须先扫码登录吗？上送appid和这个用户在这个小程序的openid，能否进行登录

打开正式版小程序本身是不需要登陆的，打开体验版小程序才需要登陆

另外如果小程序中通过`wx.authorize`申请授权，那么也是需要登陆的

**Comment by zengwendi** [comment]
> > 打开小程序获取用户信息必须先扫码登录吗？上送appid和这个用户在这个小程序的openid，能否进行登录
> 
> 打开正式版小程序本身是不需要登陆的，打开体验版小程序才需要登陆
> 
> 另外如果小程序中通过`wx.authorize`申请授权，那么也是需要登陆的

小程序获取手机号必须在扫码登录才能获取是吧，这样流程就比较麻烦，还有授权请求IPCInvokerTask_AuthorizeNoLogin当中scope的参数意义是什么

**Comment by simonla** [comment]
> > > 打开小程序获取用户信息必须先扫码登录吗？上送appid和这个用户在这个小程序的openid，能否进行登录
> > 
> > 
> > 打开正式版小程序本身是不需要登陆的，打开体验版小程序才需要登陆
> > 另外如果小程序中通过`wx.authorize`申请授权，那么也是需要登陆的
> 
> 小程序获取手机号必须在扫码登录才能获取是吧，这样流程就比较麻烦，还有授权请求IPCInvokerTask_AuthorizeNoLogin当中scope的参数意义是什么

scope参考demo，填`“snsapi_userinfo,snsapi_runtime_apk"`即可

**Comment by simonla** [comment]
有新的问题请新开issue吧，这样方便后来的开发者参考，谢谢大家了~

这个issue就先close掉了

**Comment by charjack** [comment]
请问下，在launchWxa的时候，有遇到这个报错吗？“no activate  10006”

**Comment by charjack** [comment]
> log无异常，流程细节点都有仔细比对过，用的是小米Note3手机测试，如方便，还请指导下，比较着急调研，联系邮箱[rptangCN@icloud.com](mailto:rptangCN@icloud.com)

你好，请问你的问题解决了，我的问题好像是跟你一样的。前面的激活都正常，就是无法拉起小程序。
