### ISSUE TITLE
adddevice 接口报错 system error hint: [3HZo_a0917shc1]

### ISSUE THREAD

**Issue by myzingy** [wmpf/wmpf_demo_external#40]
![微信截图_20200303154015](https://user-images.githubusercontent.com/228342/75753266-640ee800-5d65-11ea-9303-96542faf8879.png)

**Comment by simonla** [comment]
[https://developers.weixin.qq.com/doc/oplatform/Miniprogram_Frame/deviceId.html]()
 参考这个填下modelname
