### ISSUE TITLE
扫码登录后回调10004，是否有一份具体的错误码说明？

### ISSUE THREAD

**Issue by zhoujia456888** [wmpf/wmpf_demo_external#44]
扫码登录之后回调 errMsg:may be missing app permissions NULL(10000)    ret:10004,这个提示是什么意思？有没有一个具体的错误码说明？

**Comment by simonla** [comment]
先在https://github.com/wmpf/wmpf_demo_external/releases更新下最新的wmpf吧

**Comment by zhoujia456888** [comment]
apk和aar都是最新的。

> 先在[这里](https://github.com/wmpf/wmpf_demo_external/releases)更新下最新的wmpf吧

apk和aar都是最新的。还是提示10004

**Comment by simonla** [comment]
* 如果是使用demo的hostAppId
发送/sdcard/wmpf/xlog下的日志文件到complexzeng@tencent.com，我们会帮忙排查给出结论

* 如果使用的自己的hostAppId
有两种可能性，需要你检查下

1. 检查代码的入参，和demo是否一致，确保入参正确
2. 你的hostAppId还没有登录权限，开通权限的路径是：[wecooper](http://wecooper.weixin.qq.com/)-申请后台接口-添加

**Comment by simonla** [comment]
查到问题了，你的hostAppId没有开通登录权限，需要在[微信开放平台](https://open.weixin.qq.com/)开通该权限

**Comment by Hazy-Huang** [comment]
在arr上搜索com.tencent.wmpf.cli.task.TaskError
