### ISSUE TITLE
体验版和正式版为什么不能调起小程序

### ISSUE THREAD

**Issue by qineyu** [wmpf/wmpf_demo_external#47]
我在测试启动发布版的小程序是可以的,但是再启动发布版的就会闪退,而且我已经是登录了的,也有体验版的权限

**Comment by Hazy-Huang** [comment]
更新最新的WMPF版本，麻烦根据demo流程进行，确定是否关闭之前的小程序，如果还是能复现的话把/sdcard/wmpf/xlog目录下的日志发送到v_yeohuang@tencent.com
