### ISSUE TITLE
do you want to open source wmpf?

### ISSUE THREAD

**Issue by luori-mvp77** [wmpf/wmpf_demo_external#5]

**Comment by kirozhao** [comment]
We can't, for now.

**Comment by luorixiangyang** [comment]
Do you intent wmpf run on others except(windows, linux)  os, e.g.  FreeRTOS、TencentOS Tiny or others IOT OS?

**Comment by dongfo** [comment]
> @kirozhao Do you intent wmpf run on others except(windows, linux) os, e.g. FreeRTOS、TencentOS Tiny or others IOT OS?

Are you serious ? FreeRTOS、TencentOS Tiny or others IOT OS? they are embeded os for limited hardware ,and do not even have as gui in most case.

**Comment by luorixiangyang** [comment]
@dongfo 
Yes, i am pay attention to TencentOS, but there no more effective infos about it.  Therefore ,  i want know if translate wechat lite app abilities to some lightly devices, like as IOT devices?

**Comment by luorixiangyang** [comment]
Maybe  wmpf + tencentos is a suitable solution for iot devices with screen.
