### ISSUE TITLE
注册了企业账号，添加设备一直处于审核中

### ISSUE THREAD

**Issue by cizkey** [wmpf/wmpf_demo_external#55]
您好，我查看readme中说到要使用要注册硬件，但是在微信终端合作平台添加设备一直处于审核中，请问这个审核要多长时间，不然没办法添加公钥啊

**Comment by guoxuzan** [comment]
请问你的审核中持续了多久啊

**Comment by guoxuzan** [comment]
guoxuzan@qq.com，能否把您的联系方式发送我邮箱呢，交流WMPF经验

**Comment by wyudong** [comment]
@guoxuzan 如果审核慢，开个 issue 叫他们帮你看下审核
