### ISSUE TITLE
魅族 MX5 使用 demo 激活设备失败 bridge not found

### ISSUE THREAD

**Issue by wyudong** [wmpf/wmpf_demo_external#58]
从 wecooper 后台下载并用魅族 MX5 安装 WMPF-arm64.apk 和 wmpf-demo.apk。后打开“微信小程序硬件框架”，再运行“WMPF Client Demo”，使用默认的 APP_ID 和 APP_SECRET，输入“小程序 ID”和 ticket 快速体验，无法打开小程序。

> 激活设备失败, error: bridge not found, 确认WMPF框架处于运行状态

/sdcard/wmpf 里的日志如下，请问不能激活设备的原因是什么？

[wmpf.zip](https://github.com/wmpf/wmpf_demo_external/files/4435909/wmpf.zip)

**Comment by simonla** [comment]
有些ROM会禁止wmpf-demo.apk拉起WMPF-arm64.apk，手动打开WMPF后再尝试一次，应该就可以激活了

**Comment by wyudong** [comment]
@simonla 手动打开 WMPF 了，显示一个白底的页面和图标，底下版本是 `7.0.9.48(200)/0x27000930/e505a220/REL`；然后切回 demo 仍然报 bridge not found。
