### ISSUE TITLE
[reopen] 魅族 MX5 使用 demo 激活设备失败 bridge not found

### ISSUE THREAD

**Issue by wyudong** [wmpf/wmpf_demo_external#59]
问题还未解决，重开 #58。

从 wecooper 后台下载并用魅族 MX5 安装 WMPF-arm64.apk 和 wmpf-demo.apk。后打开“微信小程序硬件框架”，再运行“WMPF Client Demo”，使用默认的 APP_ID 和 APP_SECRET，输入“小程序 ID”和 ticket 快速体验，无法打开小程序。

> 激活设备失败, error: bridge not found, 确认WMPF框架处于运行状态

手动开启 WMPF 仍然是 bridge not found，难道这个设备不支持吗？/sdcard/wmpf 里的日志如下。

[wmpf.zip](https://github.com/wmpf/wmpf_demo_external/files/4435909/wmpf.zip)

**Comment by simonla** [comment]
bridge not found其实就是IPC调用失败了，相关代码在ipcinvoker.aar里，代码没有混淆，可以自查原因。
一个可能的原因是ROM拦截掉了，找下设备设置里有没有运行应用后台运行的权限
