### ISSUE TITLE
Q&A 里“兜底调用LaunchWxaApp”是什么意思？

### ISSUE THREAD

**Issue by wyudong** [wmpf/wmpf_demo_external#60]
> 调用LaunchWxaApp超时，未响应:
> 一般是WMPF Service未正确启动，导致无法响应，可监听IPCInvokeCallbackEx相关失败回调并兜底调用LaunchWxaApp.

请问这里“兜底调用LaunchWxaApp”是什么意思，再调用一遍 LaunchWxaApp？

**Comment by Hazy-Huang** [comment]
文档为表达完善，已进行修改，应该是根据回调进行不同的错误处理
