### ISSUE TITLE
Demo 快速体验体验小程序，启动小程序失败

### ISSUE THREAD

**Issue by xiaoshangmin** [wmpf/wmpf_demo_external#61]
小米8  系统版本安卓9  个人开发者账号使用体验版打不开腾讯地+小程序
![A974BE438ADE5AA91EB99014CAEA70F2](https://user-images.githubusercontent.com/6623100/79354320-d8e15e80-7f6e-11ea-8bf4-2e5b3200be2e.jpg)

**Comment by simonla** [comment]
可能是系统权限问题，设置里允许下WMPF后台启动
