### ISSUE TITLE
wecooper-申请后台接口-添加  在微信终端合作平台里没有找到

### ISSUE THREAD

**Issue by gengalaixin** [wmpf/wmpf_demo_external#62]
2.你的hostAppId还没有登录权限，开通权限的路径是：wecooper-申请后台接口-添加

没有找到具体的添加页面，能否具体说明下，感谢

**Comment by wyudong** [comment]
wecooper.weixin.qq.com > 申请注册设备 > 添加

* 这文档写的无力吐槽，东一块西一块
