### ISSUE TITLE
wmpf service app 为什么要申明 launcher

### ISSUE THREAD

**Issue by markzhai** [wmpf/wmpf_demo_external#63]
本身启动也只是一个占位 activity 的话，为啥不直接干掉 launcher 呢？毕竟有意义的启动都是由 client app 发起的

**Comment by simonla** [comment]
在[releases](https://github.com/wmpf/wmpf_demo_external/releases)我们提供了两种WMPF Service代码包。alpha和production。alpha有启动页，方便调试。production是没有启动页的。
