### ISSUE TITLE
没有理解 ‘驱动程序 Driver Apps’ 是什么

### ISSUE THREAD

**Issue by xch549586205** [wmpf/wmpf_demo_external#7]

**Comment by kirozhao** [comment]
这个概念是从一般的操作系统外设驱动程序上引申出来的。

在 wmpf 运行的硬件设备中，可以根据场景增加设备自己的（广义）外设扩展，包括：
1）硬件外设：例如打印机、特有3D摄像头等；
2）软件外设：例如必须通过特定 App 进行的私有授权机制；
这些外设扩展的能力，wmpf 作为通用框架无法预先知道，也无法预先抽象出特定的调用接口及参数。

通过“驱动程序”（Driver Apps）则可封装出对 wmpf 中的小程序运行的这类特殊的私有接口，供小程序调用使用。需要注意的是，因为这类接口是特殊设备定制中的私有接口，在小程序开发者工具侧无法调用，需要通过真机进行调试。

1.0.0 版本中尚未公开具体方法，预计下一个版本会有详细的说明文档。

**Comment by xch549586205** [comment]
哦哦，大概了解了。 
还有一个问题，您在上一位朋友提出的issue回答中说到 “会给出一个简化的新方案，新方案只需要在wecooper注册后即可跑通demo”   ，请问这个方案大概何时给出。因为想做出个演示demo，整个流程确实很麻烦

**Comment by simonla** [comment]
> 哦哦，大概了解了。
> 还有一个问题，您在上一位朋友提出的issue回答中说到 “会给出一个简化的新方案，新方案只需要在wecooper注册后即可跑通demo” ，请问这个方案大概何时给出。因为想做出个演示demo，整个流程确实很麻烦

预计明天给到

**Comment by simonla** [comment]
> > 哦哦，大概了解了。
> > 还有一个问题，您在上一位朋友提出的issue回答中说到 “会给出一个简化的新方案，新方案只需要在wecooper注册后即可跑通demo” ，请问这个方案大概何时给出。因为想做出个演示demo，整个流程确实很麻烦
> 
> 预计明天给到

see [https://github.com/wmpf/wmpf_demo_external/issues/4#issuecomment-576003718](https://github.com/wmpf/wmpf_demo_external/issues/4#issuecomment-576003718)
