### ISSUE TITLE
横屏设备显示问题

### ISSUE THREAD

**Issue by DenisChow1987** [wmpf/wmpf_demo_external#71]
目前大部分小程序都是基于手机开发的竖屏模式，针对横屏设备有哪些方案，是等比缩放还是需要小程序开发者重新开发适配。

例如腾讯地图，都只有竖屏。

**Comment by simonla** [comment]
有两种方式：
1. [WMPF强制横屏居中显示](https://github.com/wmpf/wmpf_demo_external/pull/54)
2. [小程序主动适配](https://developers.weixin.qq.com/miniprogram/dev/framework/view/resizable.html)
