### ISSUE TITLE
demo 运行激活设备时总是报错提示token为空

### ISSUE THREAD

**Issue by fanchou** [wmpf/wmpf_demo_external#79]
java.lang.IllegalStateException: it.invokeToken must not be null

I/WMPF.Demo.MainActivity: success: token = null

1、产品创建了，PRODUCT_ID有了
2、设备注册成功了，可以查询到，DEVICE_ID有了
3、SIGNATURE有生成，并且校验通过，SIGNATURE有了
4、是最新的代码也试过了，也不行

**Comment by Hazy-Huang** [comment]
是否有在微信开放平台选择移动应用开发，申请hostAppId，并得到AppSecret，token是基于这个获取的

**Comment by fanchou** [comment]
> 是否有在微信开放平台选择移动应用开发，申请hostAppId，并得到AppSecret，token是基于这个获取的

有申请的，token也是根据这个拿的

**Comment by Hazy-Huang** [comment]
通常是参数填写错误，有做这一步吗？将获取到的信息填入DeviceInfo.kt及build.gradle，设置DeviceInfo.isInProductionEnv = true，然后修改定制的wmpf-client！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"周凡"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 上午8:57
收件人:&nbsp;"wmpf/wmpf_demo_external"<wmpf_demo_external@noreply.github.com&gt;;
抄送:&nbsp;"黄圳源"<420389560@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wmpf/wmpf_demo_external] demo 运行激活设备时总是报错提示token为空 (#79)





  
是否有在微信开放平台选择移动应用开发，申请hostAppId，并得到AppSecret，token是基于这个获取的
  
有申请的，token也是根据这个拿的

**Comment by fanchou** [comment]
const val isInProductionEnv = true 设了     build.gradle 中 buildConfigField  也改了。

**Comment by Hazy-Huang** [comment]
麻烦给下激活的task的返回




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"周凡"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 上午9:23
收件人:&nbsp;"wmpf/wmpf_demo_external"<wmpf_demo_external@noreply.github.com&gt;;
抄送:&nbsp;"黄圳源"<420389560@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wmpf/wmpf_demo_external] demo 运行激活设备时总是报错提示token为空 (#79)





 
const val isInProductionEnv = true 设了     build.gradle 中 buildConfigField  也改了。

**Comment by Hazy-Huang** [comment]
麻烦问下这边是用在什么场景吗？能大致说明下吗？这边可以完全用demo来，断点确定下哪个失败了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"黄圳源"<420389560@qq.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 下午2:19
收件人:&nbsp;"wmpf/wmpf_demo_external"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [wmpf/wmpf_demo_external] demo 运行激活设备时总是报错提示token为空 (#79)



麻烦给下激活的task的返回




------------------ 原始邮件 ------------------
发件人:&nbsp;"周凡"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 上午9:23
收件人:&nbsp;"wmpf/wmpf_demo_external"<wmpf_demo_external@noreply.github.com&gt;;
抄送:&nbsp;"黄圳源"<420389560@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wmpf/wmpf_demo_external] demo 运行激活设备时总是报错提示token为空 (#79)





 
const val isInProductionEnv = true 设了     build.gradle 中 buildConfigField  也改了。
