### ISSUE TITLE
启动小程序报FastExperienceActivity: error: java.lang.IllegalStateException: it.invokeToken must not be nul

### ISSUE THREAD

**Issue by zengwendi** [wmpf/wmpf_demo_external#8]
FastExperienceActivity: error: java.lang.IllegalStateException: it.invokeToken must not be nul

**Comment by simonla** [comment]
看起来是没有跑通硬件注册流程并修改[Constants](https://github.com/wmpf/wmpf_demo_external/blob/master/wmpf-demo/app/src/main/java/com/tencent/luggage/demo/wxapi/Constants.kt)导致的

后面会给到一个简化版的快速体验流程，请再等待一下

**Comment by zengwendi** [comment]
> 看起来是没有跑通硬件注册流程并修改[Constants](https://github.com/wmpf/wmpf_demo_external/blob/master/wmpf-demo/app/src/main/java/com/tencent/luggage/demo/wxapi/Constants.kt)导致的
> 
> 后面会给到一个简化版的快速体验流程，请再等待一下

ok，提交了设备一直在审核中，简化版大概什么时候出呢

**Comment by simonla** [comment]
> > 看起来是没有跑通硬件注册流程并修改[Constants](https://github.com/wmpf/wmpf_demo_external/blob/master/wmpf-demo/app/src/main/java/com/tencent/luggage/demo/wxapi/Constants.kt)导致的
> > 后面会给到一个简化版的快速体验流程，请再等待一下
> 
> ok，提交了设备一直在审核中，简化版大概什么时候出呢

see [https://github.com/wmpf/wmpf_demo_external/issues/4#issuecomment-576003718](https://github.com/wmpf/wmpf_demo_external/issues/4#issuecomment-576003718)
