### ISSUE TITLE
小程序硬件框架（WMPF）激活设备 返回错误码10012，是什么原因导致激活失败？

### ISSUE THREAD

**Issue by xianzhi33** [wmpf/wmpf_demo_external#83]
经过我们详细的复查确定激活设备所需要的productId、keyVersion、deviceId、signature、hostAppId都是正确的。但是无法激活设备，返回的错误码是10012 ，错误内容是activate device fail timeout。而且随便输入一个错误的（productId、keyVersion、deviceId、signature、hostAppId）返回的错误码依然是10012（理论上应该返回其他的错误码）。请问导致错误原因是什么，如何解决，望解答，谢谢~

**Comment by Hazy-Huang** [comment]
错误码已更新：
https://github.com/wmpf/wmpf_demo_external/wiki/Service%E4%B8%8EClient%E7%9A%84IPC%E4%BA%A4%E4%BA%92%E5%8D%8F%E8%AE%AE#%E9%94%99%E8%AF%AF%E7%A0%81-errcode
![Uploading image.png…]()
